config/routes.rb
Rails.application.routes.draw do
  resources :calls
  resources :clients
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :client
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :calls
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:clients] = 10
    include Pagy::Backend
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_call, only: %i[ show edit update destroy ]

  # GET /calls or /calls.json
  def index
    @client_id = params[:client_id]
    @calls = Call.where(client_id: @client_id)
  end

  # GET /calls/1 or /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls or /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to call_url(@call), notice: "Call was successfully created." }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1 or /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to call_url(@call), notice: "Call was successfully updated." }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1 or /calls/1.json
  def destroy
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url, notice: "Call was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def call_params
      params.require(:call).permit(:reason, :detail, :client_id)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
    @pagy, @clients = pagy(@clients)
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/calls/_call.html.erb
<div id="<%= dom_id call %>">
  <p>
    <strong>Reason:</strong>
    <%= call.reason %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= call.detail %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= call.client_id %>
  </p>

</div>

app/views/calls/_form.html.erb
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :reason, style: "display: block" %>
    <%= form.text_field :reason %>
  </div>

  <div>
    <%= form.label :detail, style: "display: block" %>
    <%= form.text_field :detail %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Show this call", @call %> |
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Calls</h1>

<div id="calls">
  <% @calls.each do |call| %>
    <%= render call %>
    <p>
      <%= link_to "Show this call", call %>
    </p>
  <% end %>
</div>

<%= link_to "New call", new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render "form", call: @call %>

<br>

<div>
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @call %>

<div>
  <%= link_to "Edit this call", edit_call_path(@call) %> |
  <%= link_to "Back to calls", calls_path %>

  <%= button_to "Destroy this call", @call, method: :delete %>
</div>

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
      <th scope="row">
        <%= client.id %>
      </th>
      <th scope="row">
        <%= client.name %>
      </th>
      <td scope="row">
        <%= client.phone %>
      </td>
      <td scope="row">
        <%= client.email %>
      </td>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>
<%= link_to "New client", new_client_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Telefono</th>
      <th scope="col">Email</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>

    <% @clients.each do |client| %>
      <tr>
        <%= render client %>

          <td colspan="3">
            <%= link_to "Llamadas", calls_path(client_id: client.id) %>
            <%= link_to "Editar", edit_client_path(client) %>
            <%= button_to "Destroy", client, method: :delete %>
          </td>


      </tr>
    <% end %>

  </tbody>
</table>
<%=raw pagy_nav(@pagy)%>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Callcenter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>